//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinorsoft.NHNN.Report.DTO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Vinorsoft_NHNN_Report_DevEx_DTO_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vinorsoft_NHNN_Report_DevEx_DTO_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vinorsoft.NHNN.Report.DTO.Vinorsoft.NHNN.Report.DevEx.DTO.Resource", typeof(Vinorsoft_NHNN_Report_DevEx_DTO_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string AccessHistorical_Date {
            get {
                return ResourceManager.GetString("AccessHistorical_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bộ điều khiển.
        /// </summary>
        public static string AccessHistorical_DescriptionCircuit {
            get {
                return ResourceManager.GetString("AccessHistorical_DescriptionCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ra/Vào.
        /// </summary>
        public static string AccessHistorical_InOut {
            get {
                return ResourceManager.GetString("AccessHistorical_InOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đi muộn về sớm.
        /// </summary>
        public static string AccessHistorical_IsNoCaculate {
            get {
                return ResourceManager.GetString("AccessHistorical_IsNoCaculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ điều khiển.
        /// </summary>
        public static string AccessHistorical_LibelleCircuit {
            get {
                return ResourceManager.GetString("AccessHistorical_LibelleCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string AccessHistorical_Time {
            get {
                return ResourceManager.GetString("AccessHistorical_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vào.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ra.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cho phép (Phút).
        /// </summary>
        public static string LimitOfMinute {
            get {
                return ResourceManager.GetString("LimitOfMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biển số xe.
        /// </summary>
        public static string ReportCar_LibHisto {
            get {
                return ResourceManager.GetString("ReportCar_LibHisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng.
        /// </summary>
        public static string ReportLateSoon_Total {
            get {
                return ResourceManager.GetString("ReportLateSoon_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thời gian.
        /// </summary>
        public static string ReportOverTime_Total {
            get {
                return ResourceManager.GetString("ReportOverTime_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ điều khiển.
        /// </summary>
        public static string ReportQuickDTO_DescriptionCircuit {
            get {
                return ResourceManager.GetString("ReportQuickDTO_DescriptionCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string ReportQuickDTO_InOutDate {
            get {
                return ResourceManager.GetString("ReportQuickDTO_InOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ.
        /// </summary>
        public static string ReportQuickDTO_InOutTime {
            get {
                return ResourceManager.GetString("ReportQuickDTO_InOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng công.
        /// </summary>
        public static string ReportTimeKeeping_Total {
            get {
                return ResourceManager.GetString("ReportTimeKeeping_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string SearchReportCheckInOut_Month {
            get {
                return ResourceManager.GetString("SearchReportCheckInOut_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string SearchReportCheckInOut_Year {
            get {
                return ResourceManager.GetString("SearchReportCheckInOut_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến giờ.
        /// </summary>
        public static string SearchReportQuick_EndHour {
            get {
                return ResourceManager.GetString("SearchReportQuick_EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang trong tòa nhà.
        /// </summary>
        public static string SearchReportQuick_Inside {
            get {
                return ResourceManager.GetString("SearchReportQuick_Inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string SearchReportQuick_SearchDate {
            get {
                return ResourceManager.GetString("SearchReportQuick_SearchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ giờ.
        /// </summary>
        public static string SearchReportQuick_StartHour {
            get {
                return ResourceManager.GetString("SearchReportQuick_StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã CC.
        /// </summary>
        public static string UserConfig_CardId {
            get {
                return ResourceManager.GetString("UserConfig_CardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string UserConfig_Clot {
            get {
                return ResourceManager.GetString("UserConfig_Clot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string UserConfig_Department {
            get {
                return ResourceManager.GetString("UserConfig_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string UserConfig_FirstName {
            get {
                return ResourceManager.GetString("UserConfig_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đi trễ về sớm.
        /// </summary>
        public static string UserConfig_IsNoCaculate {
            get {
                return ResourceManager.GetString("UserConfig_IsNoCaculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string UserConfig_JobTitle {
            get {
                return ResourceManager.GetString("UserConfig_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string UserConfig_LastName {
            get {
                return ResourceManager.GetString("UserConfig_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id user.
        /// </summary>
        public static string UserConfig_UserId {
            get {
                return ResourceManager.GetString("UserConfig_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string UserList_ChucVu {
            get {
                return ResourceManager.GetString("UserList_ChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string UserList_CreationDate {
            get {
                return ResourceManager.GetString("UserList_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string UserList_Cuc {
            get {
                return ResourceManager.GetString("UserList_Cuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string UserList_FirstName {
            get {
                return ResourceManager.GetString("UserList_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã CC.
        /// </summary>
        public static string UserList_IDNumber {
            get {
                return ResourceManager.GetString("UserList_IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ.
        /// </summary>
        public static string UserList_LogicalCode {
            get {
                return ResourceManager.GetString("UserList_LogicalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string UserList_Name {
            get {
                return ResourceManager.GetString("UserList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string UserList_Phong {
            get {
                return ResourceManager.GetString("UserList_Phong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình.
        /// </summary>
        public static string UserPermitConfig_ConfigValue {
            get {
                return ResourceManager.GetString("UserPermitConfig_ConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string UserPermitConfig_Id {
            get {
                return ResourceManager.GetString("UserPermitConfig_Id", resourceCulture);
            }
        }
    }
}
