//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinorsoft.NHNN.Report.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Vinorsoft_NHNN_Report_DevEx_App_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vinorsoft_NHNN_Report_DevEx_App_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vinorsoft.NHNN.Report.App.Vinorsoft.NHNN.Report.DevEx.App.Resource", typeof(Vinorsoft_NHNN_Report_DevEx_App_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đi muộn về sớm.
        /// </summary>
        public static string AccessHistorical_IsNoCaculate {
            get {
                return ResourceManager.GetString("AccessHistorical_IsNoCaculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string All_Value {
            get {
                return ResourceManager.GetString("All_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình đi muộn về sớm.
        /// </summary>
        public static string Button_Config_Latesoon {
            get {
                return ResourceManager.GetString("Button_Config_Latesoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết ra vào.
        /// </summary>
        public static string Button_Detail {
            get {
                return ResourceManager.GetString("Button_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ra/Vào.
        /// </summary>
        public static string Colums_InOut {
            get {
                return ResourceManager.GetString("Colums_InOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string Colums_Time {
            get {
                return ResourceManager.GetString("Colums_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị: {2} | Phòng ban: {3} | Người lập: {0} | Ngày lập: {1:dd/MM/yyyy HH:mm}.
        /// </summary>
        public static string CreatorFormat {
            get {
                return ResourceManager.GetString("CreatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người lập: {0} | Ngày lập: {1:dd/MM/yyyy HH:mm}.
        /// </summary>
        public static string CreatorFormat2 {
            get {
                return ResourceManager.GetString("CreatorFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo xe.
        /// </summary>
        public static string Export_CarReport_FileName {
            get {
                return ResourceManager.GetString("Export_CarReport_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo ra vào.
        /// </summary>
        public static string Export_CheckInOut_FileName {
            get {
                return ResourceManager.GetString("Export_CheckInOut_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo đi muộn về sớm.
        /// </summary>
        public static string Export_LateSoon_FileName {
            get {
                return ResourceManager.GetString("Export_LateSoon_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo làm thêm giờ.
        /// </summary>
        public static string Export_OverTime_FileName {
            get {
                return ResourceManager.GetString("Export_OverTime_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tức thời.
        /// </summary>
        public static string Export_QuickReport_FileName {
            get {
                return ResourceManager.GetString("Export_QuickReport_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo chấm công.
        /// </summary>
        public static string Export_TimeKeeping_FileName {
            get {
                return ResourceManager.GetString("Export_TimeKeeping_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách công chức.
        /// </summary>
        public static string Export_UserList_FileName {
            get {
                return ResourceManager.GetString("Export_UserList_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng:.
        /// </summary>
        public static string Sumary_Total {
            get {
                return ResourceManager.GetString("Sumary_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công chức.
        /// </summary>
        public static string Sumary_Total_User {
            get {
                return ResourceManager.GetString("Sumary_Total_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết công chức.
        /// </summary>
        public static string User_Info {
            get {
                return ResourceManager.GetString("User_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã công chức.
        /// </summary>
        public static string UserConfig_CardId {
            get {
                return ResourceManager.GetString("UserConfig_CardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string UserConfig_Clot {
            get {
                return ResourceManager.GetString("UserConfig_Clot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string UserConfig_Department {
            get {
                return ResourceManager.GetString("UserConfig_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string UserConfig_FirstName {
            get {
                return ResourceManager.GetString("UserConfig_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đi trễ về sớm.
        /// </summary>
        public static string UserConfig_IsNoCaculate {
            get {
                return ResourceManager.GetString("UserConfig_IsNoCaculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string UserConfig_JobTitle {
            get {
                return ResourceManager.GetString("UserConfig_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string UserConfig_LastName {
            get {
                return ResourceManager.GetString("UserConfig_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id user.
        /// </summary>
        public static string UserConfig_UserId {
            get {
                return ResourceManager.GetString("UserConfig_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string UserList_ChucVu {
            get {
                return ResourceManager.GetString("UserList_ChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string UserList_CreationDate {
            get {
                return ResourceManager.GetString("UserList_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string UserList_Cuc {
            get {
                return ResourceManager.GetString("UserList_Cuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string UserList_FirstName {
            get {
                return ResourceManager.GetString("UserList_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã CC.
        /// </summary>
        public static string UserList_IDNumber {
            get {
                return ResourceManager.GetString("UserList_IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ.
        /// </summary>
        public static string UserList_LogicalCode {
            get {
                return ResourceManager.GetString("UserList_LogicalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string UserList_Name {
            get {
                return ResourceManager.GetString("UserList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string UserList_Phong {
            get {
                return ResourceManager.GetString("UserList_Phong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình.
        /// </summary>
        public static string UserPermitConfig_ConfigValue {
            get {
                return ResourceManager.GetString("UserPermitConfig_ConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string UserPermitConfig_Id {
            get {
                return ResourceManager.GetString("UserPermitConfig_Id", resourceCulture);
            }
        }
    }
}
