// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vinorsoft.Core.VDbContext;

namespace Vinorsoft.Core.VDbContext.Migrations.CoreRequestLogDb
{
    [DbContext(typeof(CoreRequestLogDbContext))]
    [Migration("20200925044311_CoreRequestLogDbContextV1")]
    partial class CoreRequestLogDbContextV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vinorsoft.Core.Entities.CoreRequestLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<bool>("Active");

                    b.Property<string>("Area");

                    b.Property<string>("Body");

                    b.Property<string>("Controller");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<bool>("Deleted");

                    b.Property<string>("FullName");

                    b.Property<string>("Host");

                    b.Property<bool>("IsAjaxRequest");

                    b.Property<string>("Method");

                    b.Property<string>("Path");

                    b.Property<string>("StatusCode");

                    b.Property<Guid?>("TenantId");

                    b.Property<DateTime?>("Updated");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Sys_CoreRequestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
