//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTApp.Core.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTApp.Core.Resources.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        internal static string _10001 {
            get {
                return ResourceManager.GetString("_10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        internal static string _10002 {
            get {
                return ResourceManager.GetString("_10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha không đúng.
        /// </summary>
        internal static string _10003 {
            get {
                return ResourceManager.GetString("_10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên làm việc không hợp lệ.
        /// </summary>
        internal static string _10004 {
            get {
                return ResourceManager.GetString("_10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động tạo mã không thành công.
        /// </summary>
        internal static string _10005 {
            get {
                return ResourceManager.GetString("_10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận không đúng hoặc hết hạn.
        /// </summary>
        internal static string _10006 {
            get {
                return ResourceManager.GetString("_10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        internal static string _10007 {
            get {
                return ResourceManager.GetString("_10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã kích hoạt.
        /// </summary>
        internal static string _10008 {
            get {
                return ResourceManager.GetString("_10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại mã xác nhận không hợp lệ.
        /// </summary>
        internal static string _10009 {
            get {
                return ResourceManager.GetString("_10009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái xác nhận không tồn tại.
        /// </summary>
        internal static string _10010 {
            get {
                return ResourceManager.GetString("_10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận chỉ gửi sau mỗi 5 phút.
        /// </summary>
        internal static string _10011 {
            get {
                return ResourceManager.GetString("_10011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái thông báo không hợp lệ.
        /// </summary>
        internal static string _10012 {
            get {
                return ResourceManager.GetString("_10012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại trạng thái thông báo không hợp lệ.
        /// </summary>
        internal static string _10013 {
            get {
                return ResourceManager.GetString("_10013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu thông báo không tồn tại.
        /// </summary>
        internal static string _10014 {
            get {
                return ResourceManager.GetString("_10014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string _10015 {
            get {
                return ResourceManager.GetString("_10015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng không tồn tại.
        /// </summary>
        internal static string _10016 {
            get {
                return ResourceManager.GetString("_10016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã được sử dụng.
        /// </summary>
        internal static string _10017 {
            get {
                return ResourceManager.GetString("_10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới phải khác mật khẩu cũ.
        /// </summary>
        internal static string _10018 {
            get {
                return ResourceManager.GetString("_10018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        internal static string _10019 {
            get {
                return ResourceManager.GetString("_10019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã được sử dụng.
        /// </summary>
        internal static string _10020 {
            get {
                return ResourceManager.GetString("_10020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản bị khóa.
        /// </summary>
        internal static string _10021 {
            get {
                return ResourceManager.GetString("_10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái người dùng không tồn tại.
        /// </summary>
        internal static string _10022 {
            get {
                return ResourceManager.GetString("_10022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đúng.
        /// </summary>
        internal static string _10023 {
            get {
                return ResourceManager.GetString("_10023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được kích hoạt.
        /// </summary>
        internal static string _10024 {
            get {
                return ResourceManager.GetString("_10024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa trạng thái thất bại.
        /// </summary>
        internal static string _10025 {
            get {
                return ResourceManager.GetString("_10025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset mật khẩu thất bại.
        /// </summary>
        internal static string _10026 {
            get {
                return ResourceManager.GetString("_10026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không hỗ trợ tải lên.
        /// </summary>
        internal static string _10027 {
            get {
                return ResourceManager.GetString("_10027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không tồn tại.
        /// </summary>
        internal static string _10028 {
            get {
                return ResourceManager.GetString("_10028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại.
        /// </summary>
        internal static string _10029 {
            get {
                return ResourceManager.GetString("_10029", resourceCulture);
            }
        }
    }
}
