//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinorsoft.Core.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vinorsoft.Core.Resx.NotificationResource", typeof(NotificationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thiết bị.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpoPushToken.
        /// </summary>
        public static string ExpoPushToken {
            get {
                return ResourceManager.GetString("ExpoPushToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách thiết bị.
        /// </summary>
        public static string Export_DeviceToken_FileName {
            get {
                return ResourceManager.GetString("Export_DeviceToken_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu thông báo .
        /// </summary>
        public static string Export_Emailtemplate_FileName {
            get {
                return ResourceManager.GetString("Export_Emailtemplate_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu thông báo.
        /// </summary>
        public static string Export_FCMtemplate_FileName {
            get {
                return ResourceManager.GetString("Export_FCMtemplate_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCMToken.
        /// </summary>
        public static string FCMToken {
            get {
                return ResourceManager.GetString("FCMToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị thật.
        /// </summary>
        public static string IsDevice {
            get {
                return ResourceManager.GetString("IsDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà sản xuất.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ điều hành.
        /// </summary>
        public static string OsName {
            get {
                return ResourceManager.GetString("OsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OsVersion {
            get {
                return ResourceManager.GetString("OsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id tham chiếu .
        /// </summary>
        public static string RefId {
            get {
                return ResourceManager.GetString("RefId", resourceCulture);
            }
        }
    }
}
